### ISSUE TITLE
add node with drowning=1

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-mods/maptools#17]
like `maptools:fake_walkable` but additionally with drowning enabled

## Use-cases

* Light-weight space-simulation effects
* Suffocating gas areas

I'd like to make a PR but need a :-1: or :+1: first

**Comment by Calinou** [comment]
Sounds good to me :+1: 

How about `maptools:drowning`? The description could be "Drownable Air", not sure what it should be exactly.
