### ISSUE TITLE
"Unbreakable" nodes are TNT-able

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/maptools#21]
This is an easy fix (add `on_blast = function() end` to the definitions), but I wanted to check to see if this was perhaps the intended behaviour. I can create a PR if someone else thinks it's a problem.

**Comment by Emojigit** [comment]
I think it is a very big problem. If i am a host of a TNT server, if i want to protect some place (such as spawn), i can't do it because this bug.

**Comment by Calinou** [comment]
@fluxionary or @Emojigit Feel free to open a pull request to make them non-TNT-able :slightly_smiling_face:

**Comment by fluxionary** [comment]
OK, I'll get to this today.
