### ISSUE TITLE
Setting for craftable coins

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/maptools#28]
Games that relied on coins being non-craftable and handing them out for their own currency, may be unhappy about coins suddenly being craftable.

Please make the coins not craftable again or at least add a setting that allows/disallows crafting of coins.

For my reference 671

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face: 

Use `minetest.settings:get()` and create a `settingtypes.txt` file ([example](https://github.com/minetest-mods/moreblocks/blob/master/settingtypes.txt)).

**Comment by Bastrabun** [comment]
Since its merged/PR closed/... am I supposed to close this? It obviously works.

**Comment by Calinou** [comment]
This was resolved by https://github.com/minetest-mods/maptools/pull/29, closing.

(PRs automatically close issues only if they use "resolves", "fixes", "closes", but not "solves".)
